import express from 'express'
import Database from 'better-sqlite3'
import { Jetstream } from '@bsky/jetstream'
import { env, pipeline, RawImage } from '@huggingface/transformers'
import { createInterface } from 'node:readline/promises'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'

const HOST = process.env.FEEDGEN_LISTENHOST ?? '127.0.0.1'
const PORT = Number(process.env.FEEDGEN_PORT ?? 3200)
const HOSTNAME = process.env.FEEDGEN_HOSTNAME ?? 'feeds.espelunca.blue'
const SERVICE_DID = process.env.FEEDGEN_SERVICE_DID ?? `did:web:${HOSTNAME}`
const PUBLISHER_DID = process.env.FEEDGEN_PUBLISHER_DID ?? ''
const RECORD_NAME = process.env.FEEDGEN_RECORD_NAME ?? 'espelunca-br'
const FEED_NAME = process.env.FEEDGEN_DISPLAY_NAME ?? 'Espelunca BR'
const FEED_DESCRIPTION = process.env.FEEDGEN_DESCRIPTION ?? 'PT-BR: notícias, memes, tecnologia, Dead by Daylight, Fortnite e League of Legends.'
const PDS_SERVICE = process.env.PDS_SERVICE ?? 'https://espelunca.blue'
const APPVIEW = process.env.FEEDGEN_APPVIEW_URL ?? 'https://public.api.bsky.app'
const JETSTREAM = process.env.FEEDGEN_JETSTREAM_URL ?? 'https://jetstream.us-east.bsky.network'
const DATA_DIR = process.env.FEEDGEN_DATA_DIR ?? '/opt/espelunca-bluesky/feed-data'
const DB_PATH = process.env.FEEDGEN_SQLITE_LOCATION ?? `${DATA_DIR}/feed.sqlite`
const ENV_FILE = process.env.FEEDGEN_ENV_FILE ?? '/opt/espelunca-bluesky/feed.env'
const CACHE_DIR = process.env.FEEDGEN_MODEL_CACHE ?? `${DATA_DIR}/hf-cache`
const TOXICITY_MODEL = process.env.TOXICITY_MODEL ?? 'onnx-community/distilbert-multilingual-toxicity-classifier-ONNX'
const TOXICITY_THRESHOLD = Number(process.env.TOXICITY_THRESHOLD ?? 0.72)
const AI_MODEL = process.env.AI_MEDIA_MODEL ?? 'onnx-community/ai-image-detect-distilled-ONNX'
const AI_THRESHOLD = Number(process.env.AI_MEDIA_THRESHOLD ?? 0.80)
const AI_UNKNOWN = process.env.AI_MEDIA_UNKNOWN_ACTION ?? 'drop'
const RETENTION_DAYS = Number(process.env.FEEDGEN_RETENTION_DAYS ?? 7)

const TOPICS = {
  news: ['notícia','notícias','noticia','noticias','jornal','reportagem','última hora','ultima hora','brasil','política','politica','economia','eleições','eleicoes','congresso'],
  technology: ['tecnologia','tecnológico','tecnologico','programação','programacao','software','hardware','linux','android','ios','iphone','windows','macos','github','open source','código aberto','codigo aberto','python','javascript','typescript','rust','nvidia','amd','intel','cpu','gpu','smartphone','computador','servidor','cloud','nuvem','inteligência artificial','inteligencia artificial','llm','cibersegurança','ciberseguranca'],
  memes: ['meme','memes','shitpost','shitposting','humor','piada','piadas','kkkk','kkkkk','rsrs','huehue','meme brasileiro','memes brasileiros','br meme'],
  dbd: ['dead by daylight','#dbd','deadbydaylight','behaviour interactive','killer de dbd','sobrevivente de dbd','survivor de dbd','perk de dbd','perks de dbd'],
  fortnite: ['fortnite','#fortnite','fncs','fortnite festival','fortnite ranked'],
  'league-of-legends': ['league of legends','#leagueoflegends','#lol','riot games','lolzinho',"summoner's rift",'summoners rift','league ranked','ranked do lol','partida de lol']
}
const NEWS_HOST_HINTS = ['agenciabrasil','g1.','uol.','terra.','metropoles.','cnnbrasil','bbc.','reuters.','apnews.','jovempan.','poder360.']
const BLOCKED_DOMAINS = ['folha.uol.com.br','estadao.com.br','valor.globo.com','nytimes.com','wsj.com','ft.com','economist.com','washingtonpost.com','bloomberg.com','theatlantic.com','newyorker.com','wired.com','t.co','bit.ly','tinyurl.com','lnkd.in','buff.ly','ow.ly','is.gd','t.ly']
const AI_MARKERS = ['gerado por ia','gerada por ia','gerados por ia','geradas por ia','feito por ia','feita por ia','criado por ia','criada por ia','imagem de ia','imagem gerada','vídeo gerado','video gerado','vídeo por ia','video por ia','ai generated','generated by ai','ai-generated','midjourney','stable diffusion','dall-e','dall·e','flux ai','flux.1','comfyui','automatic1111','sora','veo','runway ml','generative ai','generative video','synthetic media','synthetic image']

env.cacheDir = CACHE_DIR
env.allowRemoteModels = true
env.allowLocalModels = false
let toxicityPipe
let aiPipe

const norm = (v = '') => String(v).normalize('NFKC').toLocaleLowerCase('pt-BR').replace(/\s+/g,' ').trim()
const textOf = (r) => norm([r?.text,r?.embed?.external?.title,r?.embed?.external?.description].filter(Boolean).join(' '))
const isPtBr = (r) => (r?.langs ?? []).map(String).some((l) => l.toLowerCase() === 'pt-br')
const urlsOf = (r) => {
  const out = new Set()
  for (const u of String(r?.text ?? '').match(/https?:\/\/[^\s<>()\[\]{}]+/gi) ?? []) out.add(u.replace(/[.,!?;:]+$/g,''))
  for (const f of r?.facets ?? []) for (const x of f?.features ?? []) if (typeof x?.uri === 'string') out.add(x.uri)
  const visit = (e) => { if (!e || typeof e !== 'object') return; if (typeof e?.external?.uri === 'string') out.add(e.external.uri); visit(e.media) }
  visit(r?.embed)
  return [...out]
}
const hostOf = (u) => { try { return new URL(u).hostname.toLowerCase().replace(/^www\./,'') } catch { return '' } }
const blockedUrl = (u) => { try { const x = new URL(u); if (!['http:','https:'].includes(x.protocol)) return true; const h=x.hostname.toLowerCase().replace(/^www\./,''); return BLOCKED_DOMAINS.some(d=>h===d||h.endsWith('.'+d)) } catch { return true } }
const hasAiMarker = (r) => AI_MARKERS.some(m => textOf(r).includes(norm(m)))
const mediaKinds = (r) => {
  const kinds = new Set()
  const visit = (e) => { if (!e || typeof e !== 'object') return; const t=String(e.$type??''); if (t.endsWith('#images')) kinds.add('image'); if (t.endsWith('#video')) kinds.add('video'); if (t.endsWith('#gallery')) kinds.add('image'); visit(e.media) }
  visit(r?.embed)
  return [...kinds]
}
const topic = (r) => {
  const t = textOf(r)
  let best = null
  for (const [name,terms] of Object.entries(TOPICS)) {
    const hits = terms.reduce((n,term)=>n+(t.includes(norm(term))?1:0),0)
    if (hits) { const score = hits * (name==='news'?5:name==='technology'||name==='memes'?4:3); if (!best || score>best.score) best={name,score} }
  }
  for (const u of urlsOf(r)) if (NEWS_HOST_HINTS.some(h=>hostOf(u).includes(h)) && (!best || best.name!=='news')) best={name:'news',score:6}
  return best
}
function cheapFilter(r) {
  if (!isPtBr(r)) return 'language'
  if (!topic(r)) return 'topic'
  if (urlsOf(r).some(blockedUrl)) return 'blocked-domain'
  if (hasAiMarker(r)) return 'ai-marker'
  if ((r?.labels??[]).some(x=>['hate','harassment','spam','scam'].includes(String(x?.val??x?.value??'').toLowerCase()))) return 'label'
  return null
}
const db = () => {
  mkdirSync(dirname(DB_PATH), {recursive:true})
  const d = new Database(DB_PATH)
  d.pragma('journal_mode=WAL')
  d.exec(`CREATE TABLE IF NOT EXISTS post(
    uri TEXT PRIMARY KEY,cid TEXT NOT NULL,authorDid TEXT NOT NULL,createdAt TEXT NOT NULL,
    topic TEXT NOT NULL,topicScore INTEGER NOT NULL,text TEXT NOT NULL,recordJson TEXT NOT NULL,
    status TEXT NOT NULL,toxicityScore REAL,aiScore REAL,reason TEXT,insertedAt TEXT NOT NULL
  ); CREATE INDEX IF NOT EXISTS post_feed ON post(status,createdAt DESC,uri DESC); CREATE INDEX IF NOT EXISTS post_pending ON post(status,insertedAt ASC);`)
  return d
}
async function toxicity(text) {
  if (!text.trim()) return 0
  toxicityPipe ??= pipeline('text-classification', TOXICITY_MODEL, {device:'wasm'})
  const out = await (await toxicityPipe)(text,{top_k:null})
  const xs = Array.isArray(out)?out:[out]
  return Math.max(0,...xs.filter(x=>String(x?.label??'').toLowerCase().includes('toxic') && !String(x?.label??'').toLowerCase().includes('not-toxic')).map(x=>Number(x.score??0)))
}
async function mediaThumbs(uri) {
  const r = await fetch(`${APPVIEW}/xrpc/app.bsky.feed.getPosts?uris=${encodeURIComponent(uri)}`)
  if (!r.ok) throw new Error(`AppView ${r.status}`)
  const post = (await r.json())?.posts?.[0]
  const out=[]
  const add=(u)=>{try{const x=new URL(u); if(!['https:'].includes(x.protocol))return; const h=x.hostname.toLowerCase(); if((h==='cdn.bsky.app'||h.endsWith('.cdn.bsky.app')||h==='video.bsky.app')&&!out.includes(u))out.push(u)}catch{}}
  const visit=(e)=>{if(!e||typeof e!=='object')return; for(const i of e.images??[])add(i.thumb); for(const i of e.items??[])add(i.thumb); add(e.thumbnail); visit(e.media)}
  visit(post?.embed)
  return out.slice(0,4)
}
async function syntheticScore(uri,r) {
  if (!mediaKinds(r).length) return {score:0}
  const thumbs = await mediaThumbs(uri)
  if (!thumbs.length) return {unknown:true,reason:'media-not-inspectable'}
  aiPipe ??= pipeline('image-classification', AI_MODEL, {device:'wasm'})
  let score=0
  for (const u of thumbs) {
    const out=await aiPipe(await RawImage.read(u))
    const xs=Array.isArray(out)?out:[out]
    for(const x of xs) if(['fake','ai','generated','synthetic'].some(k=>String(x?.label??'').toLowerCase().includes(k))) score=Math.max(score,Number(x.score??0))
  }
  return {score}
}
function feedUri(){return PUBLISHER_DID?`at://${PUBLISHER_DID}/app.bsky.feed.generator/${RECORD_NAME}`:null}

async function start() {
  const d=db()
  const insert=d.prepare(`INSERT INTO post(uri,cid,authorDid,createdAt,topic,topicScore,text,recordJson,status,insertedAt)
    VALUES(@uri,@cid,@authorDid,@createdAt,@topic,@topicScore,@text,@recordJson,'pending',@insertedAt)
    ON CONFLICT(uri) DO UPDATE SET cid=excluded.cid,recordJson=excluded.recordJson,status='pending',reason=NULL,toxicityScore=NULL,aiScore=NULL`)
  const del=d.prepare('DELETE FROM post WHERE uri=?')
  const pending=d.prepare("SELECT * FROM post WHERE status='pending' ORDER BY insertedAt ASC LIMIT 1")
  const count=d.prepare("SELECT COUNT(*) count FROM post WHERE status='pending'")
  const mark=d.prepare('UPDATE post SET status=?,toxicityScore=?,aiScore=?,reason=? WHERE uri=?')
  const purge=d.prepare("DELETE FROM post WHERE createdAt < datetime('now', ?)")
  async function worker(){
    for(;;){
      const row=pending.get()
      if(!row){await new Promise(r=>setTimeout(r,100));continue}
      try{
        const r=JSON.parse(row.recordJson)
        const ts=await toxicity(r.text??'')
        if(ts>=TOXICITY_THRESHOLD){mark.run('rejected',ts,null,'toxicity',row.uri);continue}
        let ms={score:0}
        if(mediaKinds(r).length) ms=await syntheticScore(row.uri,r)
        if(ms.unknown && AI_UNKNOWN==='drop'){mark.run('rejected',ts,null,ms.reason,row.uri);continue}
        if(ms.score>=AI_THRESHOLD){mark.run('rejected',ts,ms.score,'ai-media',row.uri);continue}
        mark.run('accepted',ts,ms.score,'',row.uri)
      }catch(e){mark.run('rejected',null,null,`processing-error:${String(e?.message??e).slice(0,120)}`,row.uri)}
    }
  }
  async function ingest(){
    const js=new Jetstream(JETSTREAM)
    for await(const evt of js.live({kinds:['commit'],collections:['app.bsky.feed.post']})){
      if(!evt?.commit || evt.commit.collection!=='app.bsky.feed.post')continue
      const uri=`at://${evt.did}/app.bsky.feed.post/${evt.commit.rkey}`
      if(evt.commit.operation==='delete'){del.run(uri);continue}
      if(evt.commit.operation!=='create' && evt.commit.operation!=='update')continue
      const r=evt.commit.record; if(!r)continue
      const reason=cheapFilter(r); if(reason)continue
      const t=topic(r)
      insert.run({uri,cid:evt.commit.cid,authorDid:evt.did,createdAt:new Date(r.createdAt).toISOString(),topic:t.name,topicScore:t.score,text:String(r.text??''),recordJson:JSON.stringify(r),insertedAt:new Date().toISOString()})
    }
  }
  void worker(); void ingest()
  setInterval(()=>{try{purge.run(`-${RETENTION_DAYS} days`)}catch{}},3600000)
  const app=express(); app.disable('x-powered-by')
  app.get('/health',(_q,s)=>s.json({ok:true,publisherConfigured:Boolean(PUBLISHER_DID),feed:feedUri(),pending:Number(count.get().count)}))
  app.get('/.well-known/did.json',(_q,s)=>s.json({'@context':['https://www.w3.org/ns/did/v1'],id:SERVICE_DID,service:[{id:'#bsky_fg',type:'BskyFeedGenerator',serviceEndpoint:`https://${HOSTNAME}`}] }))
  app.get('/xrpc/app.bsky.feed.describeFeedGenerator',(_q,s)=>s.json({did:SERVICE_DID,feeds:feedUri()?[{uri:feedUri()}]:[]}))
  app.get('/xrpc/app.bsky.feed.getFeedSkeleton',(q,s)=>{
    const expected=feedUri()
    if(!expected||String(q.query.feed??'')!==expected)return s.status(400).json({error:'UnsupportedAlgorithm',message:'Unsupported algorithm'})
    const limit=Math.min(Math.max(Number(q.query.limit??50),1),100)
    let created=new Date().toISOString(), uri='\uffff'
    if(q.query.cursor){try{const c=JSON.parse(Buffer.from(String(q.query.cursor),'base64url').toString());created=c.created;uri=c.uri}catch{}}
    const rows=d.prepare("SELECT uri,createdAt FROM post WHERE status='accepted' AND (createdAt<? OR(createdAt=? AND uri<?)) ORDER BY createdAt DESC,uri DESC LIMIT ?").all(created,created,uri,limit)
    const body={feed:rows.map(r=>({post:r.uri}))}
    if(rows.length)body.cursor=Buffer.from(JSON.stringify({created:rows.at(-1).createdAt,uri:rows.at(-1).uri})).toString('base64url')
    s.json(body)
  })
  app.get('/',(_q,s)=>s.type('text/plain').send(`${FEED_NAME}\n\n${FEED_DESCRIPTION}\n`))
  app.listen(PORT,HOST,()=>console.log(`Feed Generator ${FEED_NAME} on http://${HOST}:${PORT}`))
}

async function fetchJson(url, options = {}){
  const r = await fetch(url, options)
  const j = await r.json().catch(() => ({}))
  if(!r.ok) throw new Error(`${url} HTTP ${r.status}: ${JSON.stringify(j)}`)
  return j
}
function didWebUrl(did){
  const parts = did.split(':').slice(2)
  if(!parts.length) throw new Error('DID did:web inválido')
  const host = parts.shift()
  const path = parts.map(x => decodeURIComponent(x)).join('/')
  return `https://${host}${path ? `/${path}/did.json` : '/.well-known/did.json'}`
}
async function resolveDidDocument(did){
  if(did.startsWith('did:plc:')) return fetchJson(`https://plc.directory/${encodeURIComponent(did)}`)
  if(did.startsWith('did:web:')) return fetchJson(didWebUrl(did))
  throw new Error(`Método DID não suportado para descoberta automática: ${did.split(':').slice(0,2).join(':')}`)
}
function pdsFromDidDocument(doc){
  const service = Array.isArray(doc?.service) ? doc.service : []
  const entry = service.find(x => x?.id === '#atproto_pds' || String(x?.id ?? '').endsWith('#atproto_pds'))
  const endpoint = String(entry?.serviceEndpoint ?? '').trim().replace(/\/$/, '')
  if(!endpoint || new URL(endpoint).protocol !== 'https:') throw new Error('DID Document não informou um PDS HTTPS válido')
  return endpoint
}
async function resolvePublisherPds(identifier){
  const value = identifier.trim().replace(/^@/,'')
  let did = value
  if(!value.startsWith('did:')){
    let handle = value
    if(!handle.includes('.')){
      try {
        const host = new URL(PDS_SERVICE).hostname
        handle = handle + '.' + host
      } catch {}
    }
    const encoded = encodeURIComponent(handle)
    let resolved
    try {
      resolved = await fetchJson(`${PDS_SERVICE}/xrpc/com.atproto.identity.resolveHandle?handle=${encoded}`)
    } catch {
      resolved = await fetchJson(`https://bsky.social/xrpc/com.atproto.identity.resolveHandle?handle=${encoded}`)
    }
    did = String(resolved?.did ?? '')
    if(!did.startsWith('did:')) throw new Error(`Não foi possível resolver o handle "${handle}" para um DID`)
  }
  const doc = await resolveDidDocument(did)
  if(doc?.id && doc.id !== did) throw new Error('DID Document retornou um DID diferente do identificador informado')
  return {did, pds: pdsFromDidDocument(doc)}
}
async function xrpc(baseUrl,method,body,accessJwt=''){
  const headers={'content-type':'application/json'}
  if(accessJwt) headers.authorization=`Bearer ${accessJwt}`
  const r=await fetch(`${baseUrl}/xrpc/${method}`,{method:'POST',headers,body:JSON.stringify(body)})
  const j=await r.json().catch(()=>({}))
  if(!r.ok)throw new Error(`${method} HTTP ${r.status}: ${JSON.stringify(j)}`)
  return j
}
async function publish(){
  const rl=createInterface({input:process.stdin,output:process.stdout})
  const identifier=await rl.question('Handle/DID da conta do Feed: ')
  const password=await rl.question('App Password: ')
  rl.close()
  const {did,pds}=await resolvePublisherPds(identifier)
  console.log(`PDS da conta detectado: ${pds}`)
  const session=await xrpc(pds,'com.atproto.server.createSession',{identifier:identifier.trim(),password:password.trim()})
  await xrpc(pds,'com.atproto.repo.putRecord',{repo:session.did,collection:'app.bsky.feed.generator',rkey:RECORD_NAME,validate:true,record:{$type:'app.bsky.feed.generator',did:SERVICE_DID,displayName:FEED_NAME,description:FEED_DESCRIPTION,createdAt:new Date().toISOString()}},session.accessJwt)
  let text=''; try{text=readFileSync(ENV_FILE,'utf8')}catch{}
  const line=`FEEDGEN_PUBLISHER_DID=${session.did}`
  text=/^FEEDGEN_PUBLISHER_DID=/m.test(text)?text.replace(/^FEEDGEN_PUBLISHER_DID=.*$/m,line):text+`${text&&!text.endsWith('\n')?'\n':''}${line}\n`
  mkdirSync(dirname(ENV_FILE),{recursive:true}); writeFileSync(ENV_FILE,text)
  console.log(`Publicado: at://${session.did}/app.bsky.feed.generator/${RECORD_NAME}`)
}
async function seed(){
  const d=db(), ins=d.prepare(`INSERT INTO post(uri,cid,authorDid,createdAt,topic,topicScore,text,recordJson,status,insertedAt)
    VALUES(@uri,@cid,@authorDid,@createdAt,@topic,@topicScore,@text,@recordJson,'pending',@insertedAt) ON CONFLICT(uri) DO NOTHING`)
  let n=0
  for(const q of ['meme','memes','tecnologia','notícia','dead by daylight','fortnite','league of legends']){
    const u=new URL(`${APPVIEW}/xrpc/app.bsky.feed.searchPosts`); u.searchParams.set('q',q);u.searchParams.set('lang','pt');u.searchParams.set('sort','latest');u.searchParams.set('limit','100')
    const r=await fetch(u); if(!r.ok)continue; const data=await r.json()
    for(const p of data.posts??[]){
      if(!p.record||!p.author?.did||!p.uri||!p.cid)continue
      const reason=cheapFilter(p.record); if(reason)continue
      const t=topic(p.record); ins.run({uri:p.uri,cid:p.cid,authorDid:p.author.did,createdAt:new Date(p.record.createdAt).toISOString(),topic:t.name,topicScore:t.score,text:String(p.record.text??''),recordJson:JSON.stringify(p.record),insertedAt:new Date().toISOString()});n++
    }
  }
  console.log(`Seed: ${n} candidatos enviados para moderação local.`)
}
const cmd=process.argv[2]
if(cmd==='publish')publish().catch(e=>{console.error(e);process.exitCode=1})
else if(cmd==='seed')seed().catch(e=>{console.error(e);process.exitCode=1})
else start().catch(e=>{console.error(e);process.exitCode=1})
